require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hospedes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Hospede. As you add validations to Hospede, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Hospede.create! valid_attributes
      get hospedes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hospede = Hospede.create! valid_attributes
      get hospede_url(hospede)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hospede_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      hospede = Hospede.create! valid_attributes
      get edit_hospede_url(hospede)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Hospede" do
        expect {
          post hospedes_url, params: { hospede: valid_attributes }
        }.to change(Hospede, :count).by(1)
      end

      it "redirects to the created hospede" do
        post hospedes_url, params: { hospede: valid_attributes }
        expect(response).to redirect_to(hospede_url(Hospede.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Hospede" do
        expect {
          post hospedes_url, params: { hospede: invalid_attributes }
        }.to change(Hospede, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hospedes_url, params: { hospede: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hospede" do
        hospede = Hospede.create! valid_attributes
        patch hospede_url(hospede), params: { hospede: new_attributes }
        hospede.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hospede" do
        hospede = Hospede.create! valid_attributes
        patch hospede_url(hospede), params: { hospede: new_attributes }
        hospede.reload
        expect(response).to redirect_to(hospede_url(hospede))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hospede = Hospede.create! valid_attributes
        patch hospede_url(hospede), params: { hospede: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hospede" do
      hospede = Hospede.create! valid_attributes
      expect {
        delete hospede_url(hospede)
      }.to change(Hospede, :count).by(-1)
    end

    it "redirects to the hospedes list" do
      hospede = Hospede.create! valid_attributes
      delete hospede_url(hospede)
      expect(response).to redirect_to(hospedes_url)
    end
  end
end
