require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/quartos", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Quarto. As you add validations to Quarto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Quarto.create! valid_attributes
      get quartos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      quarto = Quarto.create! valid_attributes
      get quarto_url(quarto)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_quarto_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      quarto = Quarto.create! valid_attributes
      get edit_quarto_url(quarto)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Quarto" do
        expect {
          post quartos_url, params: { quarto: valid_attributes }
        }.to change(Quarto, :count).by(1)
      end

      it "redirects to the created quarto" do
        post quartos_url, params: { quarto: valid_attributes }
        expect(response).to redirect_to(quarto_url(Quarto.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Quarto" do
        expect {
          post quartos_url, params: { quarto: invalid_attributes }
        }.to change(Quarto, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post quartos_url, params: { quarto: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested quarto" do
        quarto = Quarto.create! valid_attributes
        patch quarto_url(quarto), params: { quarto: new_attributes }
        quarto.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the quarto" do
        quarto = Quarto.create! valid_attributes
        patch quarto_url(quarto), params: { quarto: new_attributes }
        quarto.reload
        expect(response).to redirect_to(quarto_url(quarto))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        quarto = Quarto.create! valid_attributes
        patch quarto_url(quarto), params: { quarto: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested quarto" do
      quarto = Quarto.create! valid_attributes
      expect {
        delete quarto_url(quarto)
      }.to change(Quarto, :count).by(-1)
    end

    it "redirects to the quartos list" do
      quarto = Quarto.create! valid_attributes
      delete quarto_url(quarto)
      expect(response).to redirect_to(quartos_url)
    end
  end
end
